# Generated by Django 5.0.6 on 2024-08-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_library_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_book',
            name='lib_bookid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='read.book'),
        ),
    ]
