# Generated by Django 5.0.6 on 2024-11-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0012_readingprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
    ]
