# Generated by Django 5.0.6 on 2024-08-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='read/images')),
                ('book_genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='read.genre')),
            ],
        ),
    ]
