# Generated by Django 5.0.6 on 2024-08-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_book_book_author_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='read.genre'),
        ),
    ]
