# Generated by Django 5.0.6 on 2024-08-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_alter_book_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='library_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_bookid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='read.book')),
            ],
        ),
    ]
